Repository Wai-Technologies/raaghu-themes, pull requests merged in 2023-05, with the labels that each got.

#27 commited changes for sidenav toggler for responsiveness
  projects/rds-themes/styles/colorvariables-semidark.scss
  projects/rds-themes/styles/colorvariables.scss
  projects/rds-themes/styles/custom.scss
  projects/rds-themes/styles/side-nav.scss
Labels: enhancement

#29 Development
  projects/rds-themes/styles/colorvariables-dark.scss
  projects/rds-themes/styles/colorvariables-light.scss
  projects/rds-themes/styles/colorvariables-semidark.scss
  projects/rds-themes/styles/colorvariables.scss
  projects/rds-themes/styles/custom.scss
Labels: bug

#31 PR for set width to topnav
  projects/rds-themes/styles/custom.scss
Labels: enhancement

#37 updating warning color and horizontal navtabs on mobile view
  projects/rds-themes/styles/default.scss
  projects/rds-themes/styles/responsive.scss
Labels: enhancement

#38 Development
  projects/rds-themes/styles/button.scss
  projects/rds-themes/styles/colorvariables-dark.scss
  projects/rds-themes/styles/colorvariables-light.scss
  projects/rds-themes/styles/colorvariables-semidark.scss
  projects/rds-themes/styles/custom.scss
  projects/rds-themes/styles/datePicker.scss
  projects/rds-themes/styles/dropdown.scss
  projects/rds-themes/styles/side-nav.scss
Labels: bug, enhancement

#41 fixed password input field UI issue on RTL view
  projects/rds-icons/src/lib/icons.ts
  projects/rds-themes/styles/colorvariables-dark.scss
  projects/rds-themes/styles/colorvariables-light.scss
  projects/rds-themes/styles/colorvariables-semidark.scss
  projects/rds-themes/styles/datePicker.scss
  projects/rds-themes/styles/responsive.scss
Labels: bug

#42 Resolve the pagination issue.
  projects/rds-themes/styles/colorvariables-light.scss
  projects/rds-themes/styles/colorvariables-semidark.scss
Labels: bug

#43 Committed for button spinner
  projects/rds-themes/styles/button.scss
Labels: bug
